### ISSUE TITLE
Implement the dropdown component when the user clicks on + button to add new proposed product (copy from current)

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#105]
Mockup
![image](https://user-images.githubusercontent.com/12948375/64308613-0a02b500-cfc4-11e9-9dc0-1c30fcf5bd9d.png)

Update
![image](https://user-images.githubusercontent.com/12948375/64834508-56757280-d60c-11e9-8762-fc819b06a2cb.png)

**Comment by moewiz** [comment]
Hi @sdharmarajah, I'd like to talk about the UX flow of this component. 

As the provided design, I describe the UX flow of this component below and please confirm it.
1. The user clicks on the `+` button
![image](https://user-images.githubusercontent.com/12948375/64310156-471d7600-cfc9-11e9-9b31-c7d263322caf.png)
2. Then, a popup appears:
  - A dropdown menu gives the user a list of products to select from
  - The User selects `Product B` 
![image](https://user-images.githubusercontent.com/12948375/64310105-0faec980-cfc9-11e9-8942-aaeddc99b617.png)
  - If `Super` is selected, select all 3 nested items under that
 3. Then, the popup disappears, and `Product B` will be added to the table
![image](https://user-images.githubusercontent.com/12948375/64310095-002f8080-cfc9-11e9-8031-2c449702ff40.png)

**Comment by sdharmarajah** [comment]
Everything you mentioned is correct @moewiz 

To be 100% clear:

- If "The User selects Product B" - then only `Product B` will be added to the table

- If "The User selects Super" - then all products: `Product A`, `Product B` and `Product C` will be added to the table

**Comment by moewiz** [comment]
@sdharmarajah After the user selects `Product B`, we still keep the popup or close the popup immediately

**Comment by sdharmarajah** [comment]
We need to keep the pop-up open
Because they may want to select more than one product

What is the easiest way to implement "the user is done" @moewiz ?

I think: **Clicking outside the pop-up?**

**Comment by moewiz** [comment]
@sdharmarajah 
I agree with you that clicking outside the popup to finish this step

**Comment by sdharmarajah** [comment]
Great. Let's do that then.
