### ISSUE TITLE
DEMO TASK - [Current Section] Show "nested dropdown" for "type" column when clicking "+" button (what we have now in "Strategy section")

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#120]
See screenshot of what we have in "Strategy section" 

- 1st level of dropdown should be Client/Partner (if a Partner exists"
- 2nd level of dropdown for each section is:

1. Income (Employment | Centerlink Payment | Other Taxable | Other non taxable)
2. Expenditure (Post-Tax | Pre-Tax)
3. Assets (Lifestyle | Direct Investment | Account based pension | Transition to retirement pension | Super | Property)
4. Liabilities (Non Deductible | Deductible)

<img width="369" alt="Strategy" src="https://user-images.githubusercontent.com/8509047/65001548-760ee280-d90d-11e9-85ff-1629f2cf61a6.png">

**Comment by moewiz** [comment]
@sdharmarajah Please provide the sentence corresponding to every option user selected

**Comment by sdharmarajah** [comment]
It's not a sentence @moewiz

Just a row in the table, with the corresponding values in the column pre-selected
