### ISSUE TITLE
DEMO TASK - [Current Section] Show age in brackets

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#121]
See attached screenshot for position and calculation

![IMG_0075](https://user-images.githubusercontent.com/8509047/65001815-b15de100-d90e-11e9-8b97-211ff93e7b8c.png)

**Comment by moewiz** [comment]
@sdharmarajah please give me an example for each point:  1 and 2

**Comment by sdharmarajah** [comment]
For (1)
2019 - 1950 = 69


For (2)
2021 - 1950 = 71

@moewiz

**Comment by moewiz** [comment]
@sdharmarajah 
I think it should be:
- 20/05/11950 [69]
- The partner will retire in 2021 [71]

> Note: Always use Jul 1st as the month and day in the calculation for (2)

**Comment by sdharmarajah** [comment]
Ah. You mean the rendering

Yes, this is fine

But please use round brackets () around the # of years
