### ISSUE TITLE
DEMO TASK - Show a "processing" spinner for 3 seconds after adding "Commence an account based pension" to "Pension" section

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#132]
Where is an easy place to show this spinner, to indicate page is updating?

@moewiz @dinhnguyentrunghoa

**Comment by dinhnguyentrunghoa** [comment]
![image](https://user-images.githubusercontent.com/16713398/65480926-974b7200-debd-11e9-8894-c8a4400c248a.png)
Whenever a user changes a table, show a spinner top right of the table
When spinner disappears, update the charts with the animate effect (I discussed this with @Khoa Nguyen earlier)

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa @moewiz 

Let's implement this as follows:

**Whenever the user:**
- checks/unchecks a checkbox, 
- deletes a strategy, or
- adds a strategy

**then:**
- fetch and load the `JSON` for the page (this will be from our temporary `/demo_jsons` folder for now),
- show the spinner for 3 seconds, then
- update graphs according to the `JSON`, using the "animate" option


Important:
To make this work for the demo, all we need to take care of is:

- Check if user added "Commence an account based pension" to "Pension" section,
- If yes, then use `step_2d.json` from `/demo_jsons` folder

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa I tried to explain my thought on how to implement this 

Please confirm this is OK?

**Comment by dinhnguyentrunghoa** [comment]
@sdharmarajah That's ok

**Comment by moewiz** [comment]
@sdharmarajah 
It seems we don't have the `step_2d.json` from `/demo_jsons` yet.
The `JSON` for the Strategy page is `step_2a.json` (issue #129).

Have you had any suggestions for this case?

**Comment by sdharmarajah** [comment]
@moewiz 

I see that: after user adds "Account based pension":
- the spinner loads,
- when the spinner finishes, **THEN** "Account based pension" appears in the table

Please change **the order and font colour** after user adds "Account based pension" as follows:
- "Account based pension" should appears in the table **in grey** text
- the spinner loads,
- when the spinner finishes, THEN the added "Account based pension" should change to **black** text
