### ISSUE TITLE
Getting JSONs for Strategy section pull out drawers and graphs (before and after adding the Account Based Pension, for the demo)

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#135]
After adding the `Account Based Pension`, JSONs for pull out drawers and graphs should be updated.

TODO
---
- [x] Pull out drawers
- [x] Graphs
- [x] Strategies
- [x] KPI
- [x] Text below KPI

**Comment by moewiz** [comment]
Hi @sdharmarajah,

What is the difference between before and after adding `Account Based Pension`? Do you have any requirements for this JSON?

Or we just choose random numbers for the pull out drawers and graphs?

**Comment by sdharmarajah** [comment]
Hi @moewiz 

Before adding `Account Based Pension`: show data from `step_2a.json`


[step_2a.xlsx](https://github.com/kodiakorg/financial/files/3668757/step_2a.xlsx)
[step_2f.xlsx](https://github.com/kodiakorg/financial/files/3668758/step_2f.xlsx)
