### ISSUE TITLE
Document Screen - In Step 8, show "Active Animation Skeleton" on each tile, before loading tile data (see link)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#152]
- Rename step 8 (currently "Cost of Advice" is duplicated) to "Regulatory compliance"
See screenshot **spelling.png**

- Show the "Active Animation Skeleton" for 4 seconds, underneath tile title
https://ant.design/components/skeleton/#components-skeleton-demo-active
See screenshot **skeleton_area.png**

- After 4 seconds, fade in (with a slight right -> left animation) the tile data:
a) number (or check mark)
b) description text (if required)
c) green colour (if required)

<img width="1032" alt="skeleton_area" src="https://user-images.githubusercontent.com/8509047/67056657-97602a00-f16a-11e9-9860-9915afd8f614.png">
<img width="614" alt="spelling" src="https://user-images.githubusercontent.com/8509047/67056658-97f8c080-f16a-11e9-9371-569c66ae8ee7.png">

**Comment by sdharmarajah** [comment]
Please let me know what fade-in effect we could use for **Step 3?**

@moewiz @dinhnguyentrunghoa

**Comment by moewiz** [comment]
> Please let me know what fade-in effect we could use for **Step 3?**
> 
> @moewiz @dinhnguyentrunghoa

You mean **Step 8**, right?

**Comment by sdharmarajah** [comment]
Yes sorry, Step 8
