### ISSUE TITLE
Implement Card component

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#155]
TODO
---
- [x] ~Title has the ability to edit~
- [x] List details on the card content
- [x] If the content has many rows, it should be able to scroll.
- [x] A placeholder to add new Card
- [x] Press Enter to Create a new Card

Card
![image](https://user-images.githubusercontent.com/12948375/66100253-66adbb80-e5d4-11e9-8111-95e1eafb4488.png)

Placeholder
![image](https://user-images.githubusercontent.com/12948375/66106832-09703500-e5e9-11e9-9858-5a06ef37c24c.png)

**Comment by sdharmarajah** [comment]
@moewiz 
- Only "Added cards" by user will have "Title has the ability to edit"
See my screenshot
- The cards that come from the backend **cannot have their title edited**

![sample-5](https://user-images.githubusercontent.com/8509047/66107937-0a9c6480-e5df-11e9-8411-881a452b8d86.png)
