### ISSUE TITLE
Implement Card detail component

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#156]
TODO
---
- [x] The title has the ability to edit
- [x] The subtitle has the ability to edit
- [x] All fields in the table are editable
- [ ] ~Enter a text to the placeholder row, then a new placeholder should be added at the bottom of the table~ Ref: #157 (Modify formik values)
- [x] Table has the ability to define dynamic columns from the outside of the component
- [x] Have a carousel (to move to other cards easily
- [ ] ~`Back` button function~ ref: #157 

![image](https://user-images.githubusercontent.com/12948375/66107607-dc248680-e5ea-11e9-9b0e-7e297b5d9f45.png)

**Comment by sdharmarajah** [comment]
@moewiz 
For these 2 tasks:
- The title has the ability to edit
- The subtitle has the ability to edit

Again, user can only edit **title and subtitle** for cards that were ADDED by user

Not cards that came from backend

**Comment by sdharmarajah** [comment]
@moewiz 

When you say _"Table has the ability to define dynamic columns from the outside of the component"_

Where is **"outside of the component"** ?

**Comment by sdharmarajah** [comment]
@moewiz 
What do you plan to implement after user clicks "Back/Next" button?

**Comment by moewiz** [comment]
> @moewiz
> What do you plan to implement after user clicks "Back/Next" button?

- `Back` button: go to the Card view
- `Next` button: go to the next step

**Comment by dinhnguyentrunghoa** [comment]
> What do you plan to implement after user clicks "Back/Next" button?
As the first question which I sent, Now user can change the step by clicking on the top. So the Back / Next button function is only for next / previous  card

**Comment by sdharmarajah** [comment]
Thanks @dinhnguyentrunghoa 
I agree, this is clear to me now

**Comment by moewiz** [comment]
> @moewiz
> 
> When you say _"Table has the ability to define dynamic columns from the outside of the component"_
> 
> Where is **"outside of the component"** ?

Each step uses the table with the difference in the name of the column. So the table should allow the outside (Step 1, Step 2, etc) to define the name of columns.

**Comment by moewiz** [comment]
> @moewiz
> For these 2 tasks:
> 
> * The title has the ability to edit
> * The subtitle has the ability to edit
> 
> Again, user can only edit **title and subtitle** for cards that were ADDED by user
> 
> Not cards that came from backend

I got it. User can only edit title and subtitle for cards that were ADDED by user

**Comment by moewiz** [comment]
@sdharmarajah 
Now Back / Next button function is only for next/previous card.
My concern is we should have the way allow back from Carousel to Card.

How can the user back to Card after they are in the Carousel?

**Comment by sdharmarajah** [comment]
@moewiz Let's leave this for now

To go from Carousel to Card, we will implement https://github.com/kodiakorg/financial/issues/151

**Comment by moewiz** [comment]
@sdharmarajah 
#151 is about how user moves between the steps

I'd like to know how to go back from Card details (Carousel, see `4.png`) to Card (see `5.png`)

**Comment by sdharmarajah** [comment]
@moewiz 

Isn't this #151?

See screenshot below

They just click the step to go to the Card View

<img width="624" alt="Screen Shot 2019-10-04 at 2 52 26 PM" src="https://user-images.githubusercontent.com/8509047/66196710-a1882000-e6b6-11e9-9370-86a70fa4af04.png">
