### ISSUE TITLE
Implement functionalities of the Document section - Phase 1

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#157]
TODO
---
- [x] Step 1: apply Textarea field.
- [x] Step 2: loop the data to render the corresponding cards, switch Card and Card details view, Back and Next function, apply the table, carousel.
- [x] Step 3: loop the data to render the corresponding cards, switch Card and Card details view, Back and Next function, apply the table, carousel.
- [x] Step 4: loop the data to render the corresponding cards, switch Card and Card details view, Back and Next function, apply the table, carousel.

**Comment by sdharmarajah** [comment]
@moewiz 

What do you mean "Implement functionalities of the Document section - Phase 1" step 1,2,3,4?

What functionalities are you referring to?

**Comment by sdharmarajah** [comment]
Thanks @moewiz 

Step 2,3 and 4 are the same here - which .PNG files are you referring to?

**Comment by moewiz** [comment]
3 -> 11 .PNG files

**Comment by sdharmarajah** [comment]
Thanks @moewiz 

I hope you are not "writing 3 different logics" for Step 2,3 and 4 - since they are the same

**Comment by dinhnguyentrunghoa** [comment]
@sdharmarajah Absolutely No. We are professional
