### ISSUE TITLE
Implement functionalities of the Document section - Phase 2

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#158]
TODO
---
- [x] Step 5: apply the table view; rendering the title and subtitle based on data from the backend;
- [x] Step 6: rendering the title and subtitle based on data from the backend; loop the data to render the corresponding cards; switch Card and Card details view; apply the table; carousel: move to another slide, Back and Next function; display the placeholder card
- [x] Step 7: rendering the title and subtitle based on data from the backend; loop the data to render the corresponding cards; switch Card and Card details view; apply the table; carousel: move to another slide, Back and Next function; display the placeholder card
- [x] Step 8: rendering the title and subtitle based on data from the backend; 
- [x] In Step 8, Implement the Statistic component; based on the issues are not overwritten display the number; if all issues are overwritten, show Stick icon;
- [x] In Step 8: apply the table view; implement Action **Overwrite**, have props to CSS strikethrough and underline the issue

**Comment by sdharmarajah** [comment]
@moewiz 

What do you mean "Implement functionalities of the Document section - Phase 2" step 5,6,7,8?

What functionalities are you referring to?
