### ISSUE TITLE
Use "nested dropdown" to copy products (when clicking "+" button in Product Optimizer section)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#159]
See this spreadsheet: https://docs.google.com/spreadsheets/d/1jqn3CElTGHChv_oxkG5mP9Mx1Qg6d_nLxW6cGJVvCAM/edit?usp=sharing

And attached screenshot:
<img width="1440" alt="requirement" src="https://user-images.githubusercontent.com/8509047/66288324-670cc600-e8f6-11e9-9b89-60c7b6382c43.png">

TODO
----
- [ ] Change the current menu to cascade menu like Strategy page #163 
- [ ] Handle select an option in above menu (add a new line Plain English sentence) #164

**Comment by hoadinh2010** [comment]
- [ ] Change the current menu to cascade menu like Strategy page
- [ ] Handle select an option in above menu (add a new line Plain English sentence)
