### ISSUE TITLE
Allow "drag drop" behaviour from "Current" table to "Proposed" table (to "Replace" products)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#160]
If user drag-drops a row from "Current" table to "Proposed" table, then:

- **perform the "Replace" operation** as mentioned on the sheet:

https://docs.google.com/spreadsheets/d/1jqn3CElTGHChv_oxkG5mP9Mx1Qg6d_nLxW6cGJVvCAM/edit?usp=sharing

**Comment by hoadinh2010** [comment]
- [ ] Refactor the code of the container of  2 tables to make it can drag and drop between them
- [ ] Change the code to build 2 drag and drop columns (which are 2 tables).
- [ ] Change the row while dragging from left table to right table (re-render the row which will be the same structure of the right table )
