### ISSUE TITLE
Product Optimized page - Show the Client/Partner name in the proposed product table

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#167]

**Comment by dinhnguyentrunghoa** [comment]
The beginning should be the name of the Client or Partner (whichever tab is selected)
![image](https://user-images.githubusercontent.com/16713398/66536419-17710900-eb47-11e9-8d9c-02e4348aad71.png)

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa / @moewiz 
what do you mean here **"The beginning"** ?

**Comment by moewiz** [comment]
@sdharmarajah 
The beginning of "English plain sentence" 
![image](https://user-images.githubusercontent.com/12948375/67062311-1c5c3b00-f18d-11e9-8d0b-6c3555eed0d7.png)

**Comment by sdharmarajah** [comment]
Thanks this is clear to me now
