### ISSUE TITLE
On screen 1 of login: first click anywhere shows error (see screenshot)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#17]
<img width="1440" alt="first-click shows error" src="https://user-images.githubusercontent.com/8509047/55525468-befc1300-56ae-11e9-8c30-44be47696984.png">

**Comment by sdharmarajah** [comment]
I’ll add this to the github issue too - simple fix suggested below @dinhnguyentrunghoa @moewiz 

Why is the validation performed on focus lost?

Just perform the validation on text changed?

**Comment by haunguyen90** [comment]
@sdharmarajah 
the regular behavior of the  validation is onBlur event (which means un-focus input) the onChange text event does not makes sense because if the user is typing and you throw the error message, it's so weird

**Comment by sdharmarajah** [comment]
Your point makes sense @haunguyen90 
Then let's leave this as is for now -
Closing this, thanks
