### ISSUE TITLE
On screen 1 of login: top navigation bar should not be visible (see screenshot)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#18]
<img width="1440" alt="search bar should not be visible during sign in" src="https://user-images.githubusercontent.com/8509047/55525487-d3401000-56ae-11e9-8ec5-f442c6ab0269.png">

**Comment by vienpn91** [comment]
@sdharmarajah  @haunguyen90   @dinhnguyentrunghoa 
I fixed this task.
<img width="1872" alt="Screen Shot 2019-04-04 at 10 52 32 AM" src="https://user-images.githubusercontent.com/40975587/55528703-04790a00-56c8-11e9-9eb4-98cfac776891.png">
