### ISSUE TITLE
DEMO TASK - Change to "Clients goals" step in "Documents" section

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#184]
See screenshots (1.jpg, 2.jpg, 3.jpg)
We are: **replacing the card system and carousel** with a **new table**

**Changes in the screenshots:**
- small change to title text
- each table row has a "link" icon on LHS, like in "Product Optimizer"
- if user clicks "link", show nested dropdown with:
     - card titles from "What the advice covers" in **1st dropdown,**
     - bullet points in each card, in **2nd dropdown**
- use "placeholder" method to add new rows to table (after user sets "Goal" and "Priority" columns)
- default value in "Timeframe" column should be 2019 (use the **default ant control** to change the year. See year.png attached)

![1](https://user-images.githubusercontent.com/8509047/66801329-5aabed00-ef36-11e9-84da-5a4c1f39c66a.jpg)

![2](https://user-images.githubusercontent.com/8509047/66801561-1ec55780-ef37-11e9-8b58-5a4808256dcc.jpg)

![3](https://user-images.githubusercontent.com/8509047/66801340-5da6dd80-ef36-11e9-949d-b0d8da208291.jpg)

![year](https://user-images.githubusercontent.com/8509047/66801521-fb021180-ef36-11e9-9c9d-aa9f8802553f.png)

**Comment by dinhnguyentrunghoa** [comment]
- Implement the table
    - [ ] Layout of the table
    - [ ] Datepicker on the right table
- Implement the link function
    - [ ] Show the nested dropdown
    - [ ] Show the selected on the table row
