### ISSUE TITLE
Not showing server-generated errors (see screenshot) - use default ONLY if none sent from server

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#19]
<img width="1440" alt="not showing error from server" src="https://user-images.githubusercontent.com/8509047/55525505-e6eb7680-56ae-11e9-9548-f624460e6e73.png">

**Comment by sdharmarajah** [comment]
@moewiz 
From which API is it: "because we cannot parse the response"?

**Comment by moewiz** [comment]
@sdharmarajah 
When entering the wrong email, password, or OTP, then the request goes failed. Because browser rejects to parse response with CORS problem and throws network error, shown as 
![network_error](https://user-images.githubusercontent.com/12948375/55612164-cfe17d00-57b1-11e9-900a-5d33cc532e0f.png).

**Comment by sdharmarajah** [comment]
@moewiz 

See my screenshot - through Postman, if you enter the wrong email the reponse is OK ?

Now that we are not using self-signed certificates, this should be something from your side (React) now?

<img width="1124" alt="wrong-email" src="https://user-images.githubusercontent.com/8509047/55612637-45dfe700-57a6-11e9-9afa-dee3ef55b78b.png">

**Comment by moewiz** [comment]
Hmm... The request created by Postman is exactly the same as when you type URL on the browser and hit Enter. On the other hand, the request created by frontend using XMLHttpRequest is restricted due to security policy.

Please take a look
- ![success](https://user-images.githubusercontent.com/12948375/55613052-e38de300-57b3-11e9-98f7-3e82eeb69f9a.png)
- ![image](https://user-images.githubusercontent.com/12948375/55613134-1df78000-57b4-11e9-996f-ee996e1fa61b.png)

**Comment by sdharmarajah** [comment]
Unfortunately I cannot comment on the frontend difference :|

Can you add anything @haunguyen90

**Comment by sdharmarajah** [comment]
Does this help?

https://stackoverflow.com/questions/26045256/xmlhttprequest-cors-request-failing-even-with-access-control-allow-origin-heade

**Comment by sdharmarajah** [comment]
Is this issue resolved now @moewiz ?

**Comment by moewiz** [comment]
I see `Access-Control-Allow-Credentials` missing from response header when error occurs. Can you set

```
resp.headers['Access-Control-Allow-Credentials'] = 'true'
```
to all responses header from following APIs: `/auth/email`, `/auth/password`, `/auth/token`, `/auth/refresh`

Something like as in https://stackoverflow.com/questions/25860304/how-do-i-set-response-headers-in-flask

**Comment by sdharmarajah** [comment]
This is done @moewiz 
Can you test now?

**Comment by moewiz** [comment]
Now we face new problems.

![image](https://user-images.githubusercontent.com/12948375/55631556-85c4bf80-57e2-11e9-83f1-6e84c7eb16ea.png)

It says response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost:3000', but only one is allowed.

**Comment by sdharmarajah** [comment]
Yes, that's because earlier you asked us to:

-  add this header to **nginx**: `add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;`

- **AND** add this line to Flask:
```
@app.after_request
     def add_header(response):
          response.headers['Access-Control-Allow-Origin'] = '*'
```

So: I have **removed the nginx** line for you to test again

@moewiz @haunguyen90

**Comment by sdharmarajah** [comment]
@moewiz 

Let's coordinate a time to test this together

Will be easier to fix that way I think

Can we start at: **Monday 9 AM your time?**

**Comment by sdharmarajah** [comment]
FYI @moewiz 
I did some testing on my local machine
I was able to reproduce the issue you mentioned (running from `http://localhost:3000`)

So I went and changed the hardcoded response to allow `http://localhost:3000` (instead of the wildcard `*`) and *now it is working for me*

Hope it works for you too - let me know
