### ISSUE TITLE
DEMO TASK - Data for "Regulatory Compliance" section in "Documents" section

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#193]
See screenshot for text changes to title

Use this data:

**The Following Issues Were Flagged**
Current - None
Strategy - None
Investment - 1 Open issue
Insurance - None
Document Builder - None

**Inside the "Investment" table show this text:**
**Column 1:** CFS FirstChoice Wholesale Investments
**Column 2:** Recommended asset allocation is not inline with the John’s Balanced risk profile

![spelling2](https://user-images.githubusercontent.com/8509047/66827304-13d8ea00-ef6c-11e9-967d-2bab20ff95a7.png)

**Comment by sdharmarajah** [comment]
@moewiz the 2nd part of this issue is not done (data inside the **Investment** table)

See screenshot

--
<img width="1185" alt="Screen Shot 2019-10-18 at 8 03 59 AM" src="https://user-images.githubusercontent.com/8509047/67061440-f2e7e300-f17d-11e9-98ef-dffea081e212.png">

**Comment by moewiz** [comment]
Fixed: https://github.com/kodiakorg/financial-planning-dashboard/pull/85
