### ISSUE TITLE
On home screen: letter visible when left side tableview is collapsed (see screenshot)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#20]
<img width="738" alt="Letter visible" src="https://user-images.githubusercontent.com/8509047/55525533-0387ae80-56af-11e9-8ebc-69abf97388f1.png">

**Comment by vienpn91** [comment]
@sdharmarajah @haunguyen90 @dinhnguyentrunghoa 
I fixed this task.
 
<img width="972" alt="Screen Shot 2019-04-04 at 10 44 14 AM" src="https://user-images.githubusercontent.com/40975587/55528364-c0393a00-56c6-11e9-8676-6ae5cf82b2bc.png">
