### ISSUE TITLE
Improve formatting in "Value" columns in following tables

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#204]
In the following tables, fix formatting issues (a), (b) and (c)

1 - “Current Position” section (see example attached)
2 - pull out drawers in “Strategy” section (see example attached)
3 - “Product Optimizer” section (see example attached)
4 - Is there any other table I have missed? Please let me know

a) Change column header name from "Value" to “Value/$”
b) Remove “$” from the value entered in the column
c) Right alight the value in the column

<img width="1164" alt="1" src="https://user-images.githubusercontent.com/8509047/67250696-0a7ae080-f48a-11e9-90fb-9829ddd3333c.png">
<img width="985" alt="2" src="https://user-images.githubusercontent.com/8509047/67250697-0a7ae080-f48a-11e9-8657-d6e9a93e9789.png">
<img width="1151" alt="3" src="https://user-images.githubusercontent.com/8509047/67250698-0b137700-f48a-11e9-9e5e-7d686f807b23.png">

**Comment by moewiz** [comment]
There are other tables I think you missed:
- [ ] The pull-out drawer in Product Optimizer section ![image](https://user-images.githubusercontent.com/12948375/67256894-981ef600-f4b3-11e9-9a52-75251273d120.png)
