### ISSUE TITLE
"Strategy" section - Change text colour of rows that are NOT CHECKED to grey

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#209]
**If checked**: keep as current
**If NOT checked**: change to grey

<img width="1143" alt="unchecked" src="https://user-images.githubusercontent.com/8509047/67251809-f0430180-f48d-11e9-9827-f4c871fe7584.png">

@moewiz is it possible to animate as follows:
- when a row is "unchecked" animate it to the bottom of the table,
- when a row is "checked" animate it to the top of the table

**Comment by moewiz** [comment]
TODO:
- [ ] Phase 1: change the text color
- [ ] Phase 2: animation
