### ISSUE TITLE
Event tracking with Google Analytics

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#21]
We need to **add Google analytics for event tracking** to the our React app

I will create a Google project and share credentials with you

Will need to track:

**1 - default “common interactions”**
See “common interactions” at this link: [](https://developers.google.com/analytics/devguides/collection/gtagjs/pages)
e.g. pageviews, App/screen views, user timings an exceptions 

**2 - “custom events” which we will define**
See “Events” at this link: [](https://developers.google.com/analytics/devguides/collection/gtagjs/events)
e.g. “New client” button clicked, “+” button clicked in RHS pane
We will provide you the required strings to set for each parameter (e.g. `event_category, event_label`, etc)
We will need to be able to identify the user_id from this tracked event - 
It seems this is also possible to do with cookies: [](https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id)

Please let me know your thoughts on: 
- **how we can do this user identification** (from the tracked event?)

**Comment by haunguyen90** [comment]
> how we can do this user identification
We'll use `userId` for identifying the user. So in the login API, please ask the back-end team return the `userId` also

**Comment by sdharmarajah** [comment]
Thanks Hau

Will add this to the `data` key in the login response

How do you suggest we: share with you the events and custom data we want logged? 

Eg a shared Google sheet, or a new Github issue we 'keep updating'?

**Comment by haunguyen90** [comment]
We can use google sheet and attach that link into the issue on GitHub, but to keep updating and notifying people, you should tell everyone know every time you change the doc.

**Comment by sdharmarajah** [comment]
Hi @haunguyen90 

`user_id` is now returned with the final login API (i.e. `/token`)

Let's use this to log analytics events 

I will close this issue and open a separate issue for events

**Comment by sdharmarajah** [comment]
@moewiz 
I did not see where you are setting `user id` in the code commited?

i.e. See "2. Set up User-ID in your tracking code" in this [link](https://support.google.com/analytics/answer/3123666?hl=en)

e.g. something like this:

`ga('set', 'userId', {{USER_ID}}); // Set the user ID using signed-in user_id.`

**Comment by moewiz** [comment]
@sdharmarajah 

I thought, in the description of issue 24, we should ref to this issue. I did not recognize this requirement until now. I will create another branch to handle this.

In the future, the response of the final login API should contain a full name and avatar URL. We'll use them at the top-right corner of the main layout.

**Comment by sdharmarajah** [comment]
Thanks @moewiz 
Yes, will add these two extra params (full name, avatar URL) to the `/login` API response

**Comment by sdharmarajah** [comment]
This is done @moewiz 

Two new keys added to the `/login` response (see attached screenshot)

1. `full_name`
2. `avatar_url`

**Comment by sdharmarajah** [comment]
<img width="1152" alt="dev_test" src="https://user-images.githubusercontent.com/8509047/56105099-4885cd80-5f58-11e9-9037-7fe0f9df36ef.png">
