### ISSUE TITLE
Improved side menu style

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#210]
See attached 

<img width="1330" alt="required-screen-1" src="https://user-images.githubusercontent.com/8509047/67351287-c14e8d80-f56a-11e9-9535-537568c7ef50.png">

<img width="1330" alt="required-screen-2" src="https://user-images.githubusercontent.com/8509047/67351292-c3b0e780-f56a-11e9-85d8-6cc2ea696737.png">

**Comment by sdharmarajah** [comment]
Let me know how you plan to cycle the "background colours" for the avatar?

@moewiz

**Comment by moewiz** [comment]
@sdharmarajah Please refer to this [link](https://dev.to/marcoslooten/creating-avatars-with-colors-using-the-modulus-41g7)
