### ISSUE TITLE
"Current Position" screen - If client is married ADD "Joint" as top level dropdown to all "+" buttons

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#212]
**If the client is married:**, when clicking "+" buttons on the "Current Position" screen:

- add "Joint" as the top level dropdown (so it will be: Partner, Client, Joint)
- have the same nested options as in Client and Partner
- when creating the row in the table, set the owner to "Joint"

**Comment by moewiz** [comment]
@sdharmarajah 
Just remind you about this case.
If changing the client's marital state from `Married` to `Single`, we will change all ownerships to `Single`.
![image](https://user-images.githubusercontent.com/12948375/67450195-c6810a80-f646-11e9-8c74-4f50814436d6.png)

**Comment by sdharmarajah** [comment]
Thank you for reminding me @moewiz 

Yes this is fine - let's change ```Joint``` ownerships to ```Single``` too 👍

**Comment by moewiz** [comment]
@sdharmarajah 
Would you like to add `Joint` as an option to all dropdown Owner columns?
![image](https://user-images.githubusercontent.com/12948375/67473629-33af9280-f67d-11e9-8ad7-ddcdebe530e6.png)
