### ISSUE TITLE
"Product Optimizer" - After linking one product to a new product, update the plain English sentence (to the "Drag-drop" case)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#217]
See screenshots (#3 especially)

<img width="1160" alt="1" src="https://user-images.githubusercontent.com/8509047/67358683-cfa6a480-f57e-11e9-86b9-ffebe4b50930.png">

<img width="1159" alt="2" src="https://user-images.githubusercontent.com/8509047/67358688-d1706800-f57e-11e9-921e-28865697bc0f.png">

<img width="1160" alt="3" src="https://user-images.githubusercontent.com/8509047/67358691-d3d2c200-f57e-11e9-8f3b-200032656abe.png">

**Comment by moewiz** [comment]
@sdharmarajah 
What if user links more than 1 product?
![image](https://user-images.githubusercontent.com/12948375/67358835-c3751400-f58b-11e9-877d-83e939fccc10.png)

**Comment by sdharmarajah** [comment]
If more than 1, show it as comma separated.

e.g. If products X, Y and Z are linked, it should show:

**John Samual,** replace your existing products **X, Y** and **Z**

Do not truncate this sentence - let it span multiple lines, if required

**Comment by sdharmarajah** [comment]
@moewiz there is an "s" missing when you link multiple products

Now you have: **John Samual**, replace your existing product **X, Y** and **Z**
It should be: Now you have: **John Samual**, replace your existing products **X, Y** and **Z**

**Comment by moewiz** [comment]
Fixed: https://github.com/kodiakorg/financial-planning-dashboard/pull/90
