### ISSUE TITLE
Data entry and entering table component

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#22]
Preliminary UI/UX for data entry

Will discuss with @haunguyen90 

FYI: This is what we are in the process of finalizing now

[editing-1.pdf](https://github.com/kodiakorg/financial/files/3041856/editing-1.pdf)
[editing-2.pdf](https://github.com/kodiakorg/financial/files/3041857/editing-2.pdf)
[editing-3.pdf](https://github.com/kodiakorg/financial/files/3041858/editing-3.pdf)
[editing-4.pdf](https://github.com/kodiakorg/financial/files/3041859/editing-4.pdf)
[editing-5.pdf](https://github.com/kodiakorg/financial/files/3041860/editing-5.pdf)

## Tasks:
 - Implement layout structure for data entry tables #26
 - API mock JSON data file and storing to redux #27
 - Data entry table: Basic information, Income & Expenditure #28

**Comment by haunguyen90** [comment]
Hi @sdharmarajah 
I have some questions

1. Does your designer have the solution for the small screen? I guess the table will have the horizontal scroll and the `Action` column will be fixed.

2. Switching between tab on top (Personal, Current,...), do we need any animation such as slide right to left (similar to how we did for the login form), or just show/hide the accordingly content

3. Plus button (+) before each table's title (Income, Expenditure, Assets,...), how does it work?

4. Delete button in the `Action` column, Do we need the confirmation dialog? Or inline confirmation?

5. Plus button before each row in the table, How does it work?

6. Why does the input, select box in the very bottom of the screen are so small (see screenshot)?
![image](https://user-images.githubusercontent.com/8245883/55545310-20e06b00-56f7-11e9-9289-8c12f41dc429.png)

**Comment by sdharmarajah** [comment]
Sorry for the late reply @haunguyen90 

Let me reply below


1 - Does your designer have the solution for the small screen? I guess the table will have the horizontal scroll and the Action column will be fixed.
*Indra: Yes correct - this is the native “Fixed Columns and Header” component here: https://ant.design/components/table/#components-table-demo-fixed-columns-header*

2 - Switching between tab on top (Personal, Current,...), do we need any animation such as slide right to left (similar to how we did for the login form), or just show/hide the accordingly content
*Indra: I would prefer to keep the same consistent slide-right-to-left animation like you did earlier for the login form. Would it be difficult to change later?*

3 - Plus button (+) before each table's title (Income, Expenditure, Assets,...), how does it work?
*Indra: This should add a row to the table - using the native “Add a row” feature shown here: https://ant.design/components/table/#components-table-demo-edit-cell*

4 - Delete button in the Action column, Do we need the confirmation dialog? Or inline confirmation?
*Indra: Let’s go with the inline confirmation we discussed earlier: https://www.npmjs.com/package/react-inline-confirm*
*What do you suggest, to keep the button width fixed? The video looks a little ugly because the width changes*

5 - Plus button before each row in the table, How does it work?
*Indra: This plus button expands and collapses the grey area beneath the row in the table*
*This is also a native component: https://ant.design/components/table/#components-table-demo-expand*
*As you see, the “Assets” and “Liabilities” sections have rows with “expandable regions” *

6 - Why does the input, select box in the very bottom of the screen are so small (see screenshot)?
*Indra: These “expandable regions” have slightly smaller text with sentences*
*Sentences will have data entry in the form of: dropdowns or textfields*


*Note 1: We will provide you all sentences and data entry formats*
*Note 2: The sentences and data entry formats in these “expandable regions” COULD change based on dropdown selected in the row above*
*Note 3: Some entries in the rows are text input, some are dropdown. We will provide you all these details shortly.*

I’ll explain this clearly on a call with you - this *“customized table”* is essentially a core component we need to design and use for the data entry component

With a good design (subclasses, props, etc) we should be able to build this cleanly

**Comment by haunguyen90** [comment]
@sdharmarajah 
1. Ok

2. There's a basic tab animation in the antd lib, please check it out here: https://ant.design/components/tabs/#components-tabs-demo-basic

3. Ok

4. We can use a small popover for the confirmation box
![image](https://user-images.githubusercontent.com/8245883/55603159-808c5400-5793-11e9-9a3c-67ff98a86cbd.png)

5. Ok

6. My concern wasn't about the data & content of the `expandable regions`, it actually the looks and feels. It's a little weird to me and ugly because the input is so small and there's no padding.

**Comment by sdharmarajah** [comment]
Thanks @haunguyen90 

Replies from me:

1 - great, we will agree on this

2 - this is fine ("basic tab animation in the antd lib")

3 - great, we will agree on this

4 - let's go with the "pop confirm" dialog here
https://ant.design/components/popconfirm/#components-popconfirm-demo-icon

5 - great

6 - re: the "look and feel"
if your concern is the size and padding, these can be easily adjusted later
otherwise, do you have any other suggestions on how to improve this data capture part?

**Comment by haunguyen90** [comment]
this task is not ready yet, still under the discussion

**Comment by sdharmarajah** [comment]
@haunguyen90 @moewiz 

Before we start this task let's discuss: using [this](https://motion.ant.design/exhibition/demo/table-enter-leave) animation to add/delete a row

**Comment by sdharmarajah** [comment]
@haunguyen90 @moewiz @dinhnguyentrunghoa @vienpn91 

Thanks for your patience on this task

I believe (after my discussion with @haunguyen90 just now) we are ready to begin this

A few things to note/remember:

1 - As mentioned above, before you start the implementation, can *someone from your team* please remember to discuss [this](https://motion.ant.design/exhibition/demo/table-enter-leave) animation with me (to add/delete a row for the tables)

2 - *Updated JSON structure* is attached
Only some minor text changes and fixed an incorrect entry (the final `expandable` JSON key should have been under `coverDetails`)
You can take a `diff` to see the changes I made

3 - Reminder to @haunguyen90 to *break this task into smaller, max 4 hour subtasks*

4 - *Not very important* until you start the API integration:
But note that: the contents in the `expandable` key in the `JSON` could have a different structure, based on the `type` key in the parent object.
e.g. Look at the bottom of the markup I shared: if "Life" is selected in the "Cover Type" dropdown, the expandable region has 2 parameters *("within" and "no")*. But there could be different parameters if something else was selected in the "Cover Type" dropdown
I can discuss this with @haunguyen90 later

**Comment by sdharmarajah** [comment]
[modified-JSON-structure.json.zip](https://github.com/kodiakorg/financial/files/3103031/modified-JSON-structure.json.zip)

**Comment by sdharmarajah** [comment]
Attaching the finalized markup (data types for each field are marked here)

![Current_position_markup](https://user-images.githubusercontent.com/8509047/56552285-70081600-65a8-11e9-99b4-669c0f2c47b3.png)

**Comment by sdharmarajah** [comment]
Attaching corresponding updated JSON

Only change is to "Cover details" at bottom

You will see what I mentioned in *point 4* above:

> ".... the contents in the expandable key in the JSON could have a different structure, based on the type key in the parent object."

[modified-JSON-structure.json.zip](https://github.com/kodiakorg/financial/files/3105699/modified-JSON-structure.json.zip)

**Comment by sdharmarajah** [comment]
I know this is a large task

So important the requirement is clear to everyone **before** you start this

Can @moewiz  / @haunguyen90 / @dinhnguyentrunghoa / @vienpn91 please confirm everything is clear **before you start?**
