### ISSUE TITLE
"Strategy Section" - default data when selecting "Commence account based pension"

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#221]
When the user selects **Client -> Commence account based pension** use this as the default sentence:

**John Samual**, commence an account based pension "**(empty)**" in "**Jul 2023**" from your **CFS "FirstChoice Wholesale Super"** with "**$640,818 (Full value)**". Drawdown "**minimum pension income $(25,630)**"

**Comment by moewiz** [comment]
@sdharmarajah in the default sentence: 

> commence an account based pension "(empty)" in "Jul 2023"

Do you mean "(empty)" => ""?

**Comment by sdharmarajah** [comment]
Thanks for asking @moewiz 

I mean show the exact string: **(empty)**

:)

**Comment by moewiz** [comment]
@sdharmarajah it clear to me

**Comment by moewiz** [comment]
Thanks.
