### ISSUE TITLE
Side menu - minor improvements

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#224]
See 2 screenshots

<img width="595" alt="changes" src="https://user-images.githubusercontent.com/8509047/67442792-df29fa00-f61f-11e9-94d6-d265af32f9f2.png">

<img width="247" alt="changes-2" src="https://user-images.githubusercontent.com/8509047/67443104-22d13380-f621-11e9-82e1-4797d359724c.png">

**Comment by sdharmarajah** [comment]
@vienpn91 
One task is missing: Renaming the items

1st one should be: **November 10, 2019**
2nd one should be: **May 22, 2018**

**Comment by vienpn91** [comment]
@sdharmarajah Ok
