### ISSUE TITLE
"Strategy Section" - default data for the pull-out drawer in the "Insurance" section

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#227]
Hi @sdharmarajah, please help me provide the default data for the pull-out drawer when User click on the graph in the "Insurance" section.

![image](https://user-images.githubusercontent.com/12948375/67454047-f9310000-f652-11e9-9d51-a39ca91d6d49.png)

**Comment by sdharmarajah** [comment]
Thanks - I will get this

@moewiz
