### ISSUE TITLE
DEMO TASK - Logic when user changes date in "Account Based Pension" (Show alert and text colour change)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#228]
After step 2(d) in the demo: 
https://docs.google.com/spreadsheets/d/1KkS7QNdFW6J_jGvvLPmV8-a0WAvA_NXJeX2cxyjmtUs/edit?usp=sharing the user can change the month and year in the "Account based pension"

Please add this logic: 

1 - if the updated month and year **is LESS than the default year** (Jul 2023) then:
a) show the **"Warning" notification** here:
- https://ant.design/components/notification/#components-notification-demo-with-icon 
- http://bit.ly/2pNwnZl
b) set XX = the age of the client at updated month and year
c) bold **XX** and **employed** in the "Warning" notification
d) change the font colour of the plain English sentence to RED

2 - if the updated month and year **is >= than the default year** (Jul 2023) then: 
a) change the font colour of the plain English sentence to black

**Comment by sdharmarajah** [comment]
@moewiz 
Need some fixes here - 

1 - there **should not be an extra line break** between lines (see `warning_space.png`)

2 - we are not showing the "spinner" as discussed earlier

This is what is needed:

If the user updates month and year to LESS than the default year:
- make the font colour of the plain English sentence to **LIGHT RED, AND start the loading spinner**,
- **when the spinner finishes**, make the font colour of the plain English sentence RED

If the user updates month and year to **>= than the default year** (Jul 2023):
- make the font colour of the plain English sentence to **GREY, AND start the loading spinner**,
- **when the spinner finishes**, make the font colour of the plain English sentence BLACK



<img width="426" alt="warning_space" src="https://user-images.githubusercontent.com/8509047/67627634-688a3800-f87d-11e9-9792-231fd5ad69e4.png">

**Comment by sdharmarajah** [comment]
Text is cutoff now @moewiz 

<img width="562" alt="cutoff" src="https://user-images.githubusercontent.com/8509047/67678126-d896dc00-f9ab-11e9-8ee1-508166d6542c.png">

**Comment by moewiz** [comment]
@sdharmarajah 
Fixed on https://github.com/kodiakorg/financial-planning-dashboard/pull/93
![image](https://user-images.githubusercontent.com/12948375/67750458-d3946400-fa61-11e9-9729-bb92cfc8de4b.png)
