### ISSUE TITLE
Strategy screen: Reduce flip frequency

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#243]
Tell me how many seconds to flip charts and KPI boxes now?

<img width="545" alt="frequency?" src="https://user-images.githubusercontent.com/8509047/67627408-83f34400-f879-11e9-83f9-d7c3be9286da.png">

**Comment by moewiz** [comment]
@sdharmarajah 6 seconds

**Comment by sdharmarajah** [comment]
Thanks @moewiz

Please make it 9 seconds
