### ISSUE TITLE
[BUG] Tooltips have strange numbers

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#245]
See screenshot

<img width="557" alt="insurance_tooltips" src="https://user-images.githubusercontent.com/8509047/67627460-a043b080-f87a-11e9-99db-2ecab398c6c8.png">
<img width="549" alt="insurance_tooltips_2" src="https://user-images.githubusercontent.com/8509047/67627461-a043b080-f87a-11e9-9aae-9e0905ddd898.png">

**Comment by moewiz** [comment]
Fixed on https://github.com/kodiakorg/financial-planning-dashboard/pull/90
