### ISSUE TITLE
"Documents" -> "Client's Goals" - Show warning after deleting chip

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#249]
See `warning_2.png`

After user deletes "Income streams" chip, show same warning as earlier (http://bit.ly/2pNwnZl)
Use these details:
Title = "Warning"
Text = "All goals not addressed."

<img width="1440" alt="warning_2" src="https://user-images.githubusercontent.com/8509047/67627717-14805300-f87f-11e9-8742-ae3e6aea828a.png">

**Comment by sdharmarajah** [comment]
@moewiz 

Please let me know the extra time required to: make the row text red:

- "You would like to retire by the age of 60"
- High
- 2019

**Comment by moewiz** [comment]
@sdharmarajah I believe that I could complete this task in 1 hour.
