### ISSUE TITLE
"Presentation" - Third section (home and drilldown screens)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#252]
See attached screenshots

Third section has a **"home"** screen and **4 "drilldown" screens** (drilldown by clicking each graph on the home screen)

Each "drilldown screen" has a common template - please **build the drilldown screens with this common template**

<img width="880" alt="step3-home" src="https://user-images.githubusercontent.com/8509047/67658025-770c4880-f97e-11e9-91cc-4081862dc774.png">
<img width="931" alt="step3-drilldown-template" src="https://user-images.githubusercontent.com/8509047/67658027-770c4880-f97e-11e9-9f1f-d260703f21b0.png">

<img width="931" alt="step3-section1" src="https://user-images.githubusercontent.com/8509047/67658028-7a9fcf80-f97e-11e9-9db8-0b09a00467b6.png">
<img width="931" alt="step3-section2" src="https://user-images.githubusercontent.com/8509047/67658029-7a9fcf80-f97e-11e9-85c7-ef48c2b3f49a.png">
<img width="931" alt="step3-section3" src="https://user-images.githubusercontent.com/8509047/67658030-7b386600-f97e-11e9-9c2b-0fbdadbd2331.png">
<img width="931" alt="step3-section4" src="https://user-images.githubusercontent.com/8509047/67658032-7b386600-f97e-11e9-89f0-d059f050bd4c.png">

**Comment by moewiz** [comment]
@sdharmarajah 
I see each chart has different buttons. Please provide buttons for each chart. For example, these `Assets`, `Liabilities` and `Net Assets` buttons ![buttons](https://user-images.githubusercontent.com/8509047/67658028-7a9fcf80-f97e-11e9-9db8-0b09a00467b6.png)

**Comment by sdharmarajah** [comment]
Hi @moewiz

Yes each chart has different buttons 

The button titles you see in each image are the actual titles for each drilldown screen

**Comment by moewiz** [comment]
@sdharmarajah 
Please list the buttons for each chart.
i.e. 
- Net Assets: Income, Expenses, Net Assets
- Cashflow: button1, button2, button3.
...
![image](https://user-images.githubusercontent.com/8509047/67804261-ae264b00-fa9f-11e9-922c-bb1d14073da4.png)
