### ISSUE TITLE
"Presentation" - Third section nested dropdowns

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#253]
See screenshot for dropdowns for "Life event"

This is the only dropdown we need to implement

<img width="333" alt="plus-button-1" src="https://user-images.githubusercontent.com/8509047/67657583-33fda580-f97d-11e9-8f54-d61af248cc21.png">
<img width="335" alt="plus-button-2" src="https://user-images.githubusercontent.com/8509047/67657585-33fda580-f97d-11e9-951e-e862b3709bee.png">
<img width="341" alt="plus-button-3" src="https://user-images.githubusercontent.com/8509047/67657586-34963c00-f97d-11e9-86d6-b489de7a6bc8.png">

**Comment by moewiz** [comment]
Note: Use default **2019** instead of **2018**
