### ISSUE TITLE
"Presentation" - Third section sliders

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#254]
See screenshot

For the sliders, set these ranges and "delta" values:

**Retirement:** 
Range: 57 <= x <= 100
Increment: 1

**Income:** 
Range: $0 <= x <= $500,000
Increment: $1,000

**Expenses:** 
Range: $0 <= x <= $500,000
Increment: $1,000

**Risk profile:** 
Range: [Preservation, Defensive, Moderate, Balanced, Growth, High growth]
Increment: in the above order
See: **"step=null"** here:
https://ant.design/components/slider/#components-slider-demo-mark
Do not have any labels under the slider

Please confirm this is clear before proceeding

<img width="240" alt="sliders" src="https://user-images.githubusercontent.com/8509047/67657632-5394ce00-f97d-11e9-973b-bc479f236d9b.png">

**Comment by sdharmarajah** [comment]
Need to adjust widths/margins - 
for "High growth" - goes to 2 lines
for "Preservation" - slider changes width?

See attached videos

[Slider-width-highGrowth.mov.zip](https://github.com/kodiakorg/financial/files/3783425/Slider-width-highGrowth.mov.zip)
[Slider-width-preservation.mov.zip](https://github.com/kodiakorg/financial/files/3783426/Slider-width-preservation.mov.zip)

**Comment by sdharmarajah** [comment]
- Show "years" at the end of the first slider text

i.e. it should show *83 years* in the screenshot

<img width="325" alt="years" src="https://user-images.githubusercontent.com/8509047/67766135-ce81e580-fa5e-11e9-8155-06a62c6f39b4.png">

@moewiz

**Comment by moewiz** [comment]
> * Show "years" at the end of the first slider text
> 
> i.e. it should show **83 years** in the screenshot
> 
> <img alt="years" width="325" src="https://user-images.githubusercontent.com/8509047/67766135-ce81e580-fa5e-11e9-8155-06a62c6f39b4.png">
> 
> @moewiz
@sdharmarajah 
Should we show "years" on tooltip?

**Comment by sdharmarajah** [comment]
Yes please @moewiz
