### ISSUE TITLE
"Presentation" - Fourth section (home and drilldown screens)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#256]
Please see attached screenshots

Note:
- there is the standard "hover effect" on each button in `Step4-part1-home.png`
- every "drilldown" screen will have the same template. **So please build this once and re-use everywhere**

<img width="1006" alt="Step4-part1-home" src="https://user-images.githubusercontent.com/8509047/67679067-3c220900-f9ae-11e9-9686-dfc386b8c529.png">

**Comment by sdharmarajah** [comment]
@moewiz 

- On homescreen: **animate in** the 6 buttons, from right to left 
- On drilldown: **animate in** the image, title, and bullets in 3 sections
- Use the **same animation** as you did in the "Documents" section

See screenshots below

<img width="1006" alt="Step4-part2-drilldown-animation" src="https://user-images.githubusercontent.com/8509047/67739033-1898a600-fa22-11e9-90e4-19004e77667a.png">

<img width="1006" alt="Step4-part1-home-animation" src="https://user-images.githubusercontent.com/8509047/67739140-81801e00-fa22-11e9-9537-931d0ea95c24.png">
<img width="920" alt="animation" src="https://user-images.githubusercontent.com/8509047/67739142-8218b480-fa22-11e9-8973-7adda26ea9c6.png">

**Comment by moewiz** [comment]
@sdharmarajah

**Comment by moewiz** [comment]
@sdharmarajah 
I have a demo for animation. Please take a look and let me know if any change would make?
[animate_strategy_demo.mov.zip](https://github.com/kodiakorg/financial/files/3787035/animate_strategy_demo.mov.zip)

**Comment by sdharmarajah** [comment]
@moewiz 
Can you please use the `png` versions of the images for this screen 4?

Because it is easier for me to test with PNG than SVG

**Comment by moewiz** [comment]
Updated on https://github.com/kodiakorg/financial-planning-dashboard/pull/93
