### ISSUE TITLE
Implement layout structure for the left side menu 

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#26]
Ref: #22 

## Before
  Please check the attached image for more information about the input type for each cell
 Refer: https://xd.adobe.com/view/f23bfc14-efb0-479c-5357-593c060c1153-840a/screen/4edc8772-5049-44e4-b5a2-8c8a8e03904d/Web-1366-13?fullscreen
 
## TODO
 - [x] Left-hand side menu

   ```
     Basically, this will be a nested parent-child menu level. A client (John Samual) is a root parent 
   menu which contains multiple tasks (New, Position, Strategy,...).
      Every task will contain a child menu level: Current, Strategy, Switching, Documents, Presentation
      All Parent & child menu level can be opened & closed by clicking on its row (with caret up & down icon)
   ```

![56552285-70081600-65a8-11e9-99b4-669c0f2c47b3](https://user-images.githubusercontent.com/8245883/56554030-95058480-65ba-11e9-91ff-47c7280655fc.png)

**Comment by sdharmarajah** [comment]
Thanks @haunguyen90 
I have a sample API for this
Will try to share this today

**Comment by haunguyen90** [comment]
@sdharmarajah which API are you talking about?

**Comment by sdharmarajah** [comment]
Sorry I wasn't clear @haunguyen90 

I meant: the **API for the "Left-hand side menu"**

> Basically, this will be a nested parent-child menu level. A client (John Samual) is a root parent 
> menu which contains multiple tasks (New, Position, Strategy,...).
>    Every task will contain a child menu level: Current, Strategy, Switching, Documents, Presentation
>    All Parent & child menu level can be opened & closed by clicking on its row (with caret up & down icon)

**Comment by sdharmarajah** [comment]
@haunguyen90 @moewiz @dinhnguyentrunghoa 

Here is the API I mentioned above **for the "Left-hand side menu"**

Please see the `/homescreen` API which is documented here now: `http://bookings.odoc.life/docs`
