### ISSUE TITLE
"Presentation" - Step #7 ("Fees")

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#260]
Show a table like this here:

<img width="783" alt="Fees table" src="https://user-images.githubusercontent.com/8509047/67841484-3b51ba00-fb09-11e9-94d6-beaafda3b245.png">

Data is given below, to make it easy for you to copy-paste :)

Initial Advice | Relates to the skills, expertise and resources of our advisers and specialist consultants (where required) to formulate, model and document strategies for your financial life strategy. | SoA Preparation Fee - $500

Advice and Service | This relates to ongoing advice and services required to keep your Financial Life Strategy relevant and on track. Our client service agreement details these services. | Ongoing adviser service fee -$2,200

Investments and Platform | These are the costs charged by investment administration services and fund managers. This information is contained in product disclosure statements. | CFS Investment – 0.65%$325 based on current balance.CFS Super – 0.87%3,498 based on current balance.

**Comment by sdharmarajah** [comment]
@moewiz I updated the table data to show in this task

**Comment by moewiz** [comment]
@sdharmarajah Do we show a table like this?

![image](https://user-images.githubusercontent.com/8509047/67779414-a94ca180-fa75-11e9-90f8-9edd26195b3d.png)

**Comment by sdharmarajah** [comment]
Yes. Table like this. But different data, column names

**Comment by moewiz** [comment]
@sdharmarajah Do we align the Amount columns center?
