### ISSUE TITLE
Current Position: Match font size

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#281]
See attached screenshots

Make `Current Position` headings (marked in **YELLOW**) match:
**font size** of `Strategy` headings (marked in **RED**)

<img width="369" alt="Font-size-current-position" src="https://user-images.githubusercontent.com/8509047/68066922-ae00a680-fd50-11e9-974c-78441d485df2.png">
<img width="292" alt="Font-size-Strategy" src="https://user-images.githubusercontent.com/8509047/68066923-ae993d00-fd50-11e9-80cc-ff92794166b1.png">

**Comment by vienpn91** [comment]
@sdharmarajah 
I checked.
All title font-size as '21px' and type as bold.
