### ISSUE TITLE
Current Position - Removing sentence if Client/Partner is unemployed/retired

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#283]
See screenshot

<img width="1330" alt="retired:unemployed-plain-english-sentence" src="https://user-images.githubusercontent.com/8509047/68067120-aee70780-fd53-11e9-8f94-e7dc384b77ec.png">

**Comment by sdharmarajah** [comment]
This is not working for me @moewiz

**Comment by sdharmarajah** [comment]
@moewiz 

[Khoa-283.mov.zip](https://github.com/kodiakorg/financial/files/3822971/Khoa-283.mov.zip)

**Comment by moewiz** [comment]
Fixed on https://github.com/kodiakorg/financial-planning-dashboard/pull/109
