### ISSUE TITLE
Step 2 - Increase height of components to match other components (in row)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#286]
See screenshot

<img width="1167" alt="screen2" src="https://user-images.githubusercontent.com/8509047/68128835-87499800-ff29-11e9-9047-fd38eaf7752d.png">

**Comment by vienpn91** [comment]
please make all font size 16px
<img width="1417" alt="Screen Shot 2019-11-05 at 11 50 08 AM" src="https://user-images.githubusercontent.com/40975587/68185357-f11e7c00-ffd3-11e9-8bcd-831c94648945.png">

**Comment by vienpn91** [comment]
please make all font size 16px
<img width="933" alt="change" src="https://user-images.githubusercontent.com/40975587/68185430-14e1c200-ffd4-11e9-965d-a38c352022d2.png">
