### ISSUE TITLE
"Strategy" section - Update data in "Investment" section is wrong (JSON step 2a)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#294]

**Comment by sdharmarajah** [comment]
This is not fixed - https://github.com/kodiakorg/financial/issues/316

**Comment by moewiz** [comment]
@sdharmarajah 
I'm so sure I updated data in the "Investment" section base on the excel file you uploaded. This is screenshot
![image](https://user-images.githubusercontent.com/12948375/68359550-d3c1ed00-014e-11ea-8f0b-f39f164af9cb.png)

**Comment by sdharmarajah** [comment]
@moewiz 
Sorry - you are right - my team has filed this by mistake
This is not a bug - the data needs to be **CHANGED**
