### ISSUE TITLE
Sign-in Flow screens from designs to React & Functionalities

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#3]
Design: https://gallery.io/projects/MCHbtQVoQ2HCZZtcns12mvPd/files/MCHbtQVoQ2HCZWmDlkklwV_I

## Tasks
 - Convert and styling Sign-in screens (HTML/CSS/Animation) #8: 9hrs
 - Sign-in - Code & Logic flow implementation #9: 5hrs
 - Sign-in Flow API Call #10: 8hrs
 - Formik Implementation #11: 6hrs

## Assignment
 - Static HTML/CSS/Animation: @vienpn91 
 - Logic flow & Code implementation: @moewiz
    - Formik
    - Validation
    - API calling

**Comment by sdharmarajah** [comment]
To discuss: animation for transition to home if approved? What choices. Consider Upwork's and Apple's single field with inner transition. Any source code I can review and pick easy to integrate examples from?

**Comment by sdharmarajah** [comment]
As discussed on Thursday 21st morning call:

1) Please **copy Google's sign in style:**

a) first screen should have just one field (material design input - placeholder goes up on focus) for email address

b) When user clicks the "Next" button, until the API call returns, show a spinner on the Next button using native ant button spinner:
https://ant.design/components/modal/
See: when you click "OK" on the **"Open Modal with async" modal**

c) second screen should have just one field (material design input - placeholder goes up on focus) for password

d) There should be **no "reloading" of the page** when going from the 1st screen to the 2nd screen.
Just a "slide from Right to Left" like in the google sign in flow.

e) Show any errors (from the API response) **under the input field**, like Google
e.g. "Email address not found" and "Invalid password"

**Comment by haunguyen90** [comment]
Hi @sdharmarajah, as discussed today (March 25) on slack, we'll try to split the tasks as small as possible we can. This issue is big and lots of things to do, so I'll convert it into  `epic/story` and then create smaller tasks and associate them here.

**Comment by sdharmarajah** [comment]
Thanks @haunguyen90 
Yes, let's do that before we start this task
Ping me when you want me to review, thanks

**Comment by haunguyen90** [comment]
hi @sdharmarajah I've updated the description for this epic and create 4 related tasks for it.
