### ISSUE TITLE
"Current Position" - In Assets and Liabilities - change "Primary Residence" default owner to "Joint"

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#309]
See screenshot

<img width="1130" alt="Owner" src="https://user-images.githubusercontent.com/8509047/68315401-b9036000-00dd-11ea-8e8a-357e8b15355b.png">

<img width="1117" alt="Liabilities" src="https://user-images.githubusercontent.com/8509047/68315963-a5a4c480-00de-11ea-8d6f-14487d430b26.png">

**Comment by moewiz** [comment]
Indra: Leave the default owner as Client
