### ISSUE TITLE
"Presentation" - All pages should fit in 15" screen without vertical scrolling. Now scrolling is required

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#337]
<img width="1440" alt="make-fit-screen-1" src="https://user-images.githubusercontent.com/8509047/68404966-52497980-01a5-11ea-9574-a693e4866828.png">

<img width="1440" alt="make-fit-screen-2" src="https://user-images.githubusercontent.com/8509047/68404967-52497980-01a5-11ea-974b-db7ad8663799.png">

**Comment by moewiz** [comment]
@sdharmarajah Please provide the resolution of your screen or your laptop model. For example 2880 x 1800

**Comment by sdharmarajah** [comment]
This is not completed -
I still see some screens that do not fit - 
See attached screenshot 
There is margin you can reduce in graphs if needed
Please:
- **check all screens in this "Presentation" section** and 
- **send me a screenshot** of each one as you finish


<img width="1552" alt="not-fitting" src="https://user-images.githubusercontent.com/8509047/68495282-e1be5d80-0275-11ea-9938-8ea45d41a48e.png">
