### ISSUE TITLE
"Presentation" - Change chart colour and bar order in "Investment" section

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#340]
Balanced should be **green**
Proposed should be **red**
Current should be **blue**

**Order of bars should be**: Balanced, Proposed, Current

**Comment by moewiz** [comment]
@sdharmarajah Which screen/step you want to make the changes?
![image](https://user-images.githubusercontent.com/12948375/68445173-b9017e00-020b-11ea-90b8-6ab5a350631c.png)

**Comment by sdharmarajah** [comment]
Sorry @moewiz this is the "Investment" section (step 6)
