### ISSUE TITLE
"SOA" - Reduce "active skeleton" loading time after 1st time load 

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#360]
![timing](https://user-images.githubusercontent.com/8509047/68464971-91280f80-0237-11ea-8a30-a76773873b97.png)

**Comment by moewiz** [comment]
@sdharmarajah Currently, the loading skeleton in 4 sec.

**Comment by moewiz** [comment]
i.e.
- 1st time it will take 4s to load
- 2nd, 3rd, 4th, etc it will take 1.5s to load
