### ISSUE TITLE
Authenticated screens from designs to React & Functionalities - s3.0 - s3.3

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#4]
Design: https://gallery.io/projects/MCHbtQVoQ2HCZZtcns12mvPd/files/MCHbtQVoQ2HCZWmDlkklwV_I

Implement screens from 3.0 to 3.3

## Tasks
 - Convert and styling (HTML/CSS/Animation) - Screen 3.3 #12 
 - Screen 3.3 API calling functions #13

## Expected
 - [ ] Hover effects on user info (screen 3.3)
 - [ ] Click effects for float buttons

**Comment by sdharmarajah** [comment]
To discuss: agree on floating button. How to avoid: material vs ant confusion going forward. Not assume anything until we agree on all component behaviours + style

**Comment by sdharmarajah** [comment]
As discussed on Thursday 21st morning call: 

1 - See https://ant.design/components/tag/#components-tag-demo-control
Use the ant default "**preset style**" for the tags in the LHS subentries
So the text colour will be slightly darker than the tag colour

2 - The main entries like "John Samual" should be **expandable and collapsable** (like in a standard mail client)
Expanding should: show the sub entries and their tags
Collapsing should: hide the sub entries and their tags
Please use a good animation for this

3 - **Always** use ant default styles for components
So: **do not do any customization** of components, unless we discuss before

4 - Here are the colour codes to use for tags:
a) Position [#E9472E]
b) Strategy [#E4A140]
c) Products [#F9CC4C] 
d) Advice [#9EC341]
e) Done [#4A9F45]

**Comment by sdharmarajah** [comment]
Hi @haunguyen90 , @moewiz and @vienpn91 

I see you have implemented the “2 column layout” from ant design

This is fine - just please:

1) Make sure we can “**collapse**” this left hand menu like here:
https://ant.design/components/menu/#components-menu-demo-inline-collapsed

2) To implement (1) we will have to **reduce the width** of the search bar (not full screen like the UI design)
See attached image

**Comment by sdharmarajah** [comment]
<img width="873" alt="reduced width" src="https://user-images.githubusercontent.com/8509047/54978330-08b96f00-4fc6-11e9-93e5-b5175351076f.png">
