### ISSUE TITLE
[Investment][Proposed Pull-out Drawer] Add Button to update fund (0.5h)

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#412]
![1-AutoFund-Selection](https://user-images.githubusercontent.com/16713398/71657632-4f1cd500-2d73-11ea-81bf-309e60baba69.jpg)
Clicking this button will call an API, to *automatically set* the funds below

**Comment by sdharmarajah** [comment]
Please use the `robot` icon @dinhnguyentrunghoa

**Comment by dinhnguyentrunghoa** [comment]
We've already had this information on the image :D
