### ISSUE TITLE
[Investment] Tabs Consolidated View (1h)

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#413]
![2-Tabs-Consolidated-View](https://user-images.githubusercontent.com/16713398/71657865-3eb92a00-2d74-11ea-8411-22539c51ece6.jpg)
- [x] Add tabs like the above image
- [x] All tabs will have very similar page structure (2 tables, etc)
- [x] These tab names will come from an API
- [x] The “Consolidated” tab will have an extra column in each table for *Owner*
- [x] No PES on consolidated tab

**Comment by sdharmarajah** [comment]
Please make `Consolidated` the first tab @dinhnguyentrunghoa
