### ISSUE TITLE
[Investment][Proposed Pullout drawer] Add risk profile on the top sentences (0.5h)

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#416]
![5-RiskProfile-InBrackets](https://user-images.githubusercontent.com/16713398/71660246-fce0b180-2d7c-11ea-8ec1-b7dbe8fa6f48.jpg)

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa  I see this change was committed: https://github.com/kodiakorg/financial-planning-dashboard/pull/139

But I do not see it on the site?

https://planpod-windows.azurewebsites.net/

**Comment by dinhnguyentrunghoa** [comment]
@sdharmarajah I remembered that we don't have the right to deploy to your server. We only send you the build.zip and you take the rest
