### ISSUE TITLE
[Investment] Show Warning icon on proposed product (1h)

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#418]
![7-Warning-icon-if-issues](https://user-images.githubusercontent.com/16713398/71660348-51842c80-2d7d-11ea-850e-8b06fc05a6fb.jpg)

**Comment by sdharmarajah** [comment]
Why is this estimate 1h @dinhnguyentrunghoa ?

And I assume: you will put dummy test in the tooltip for now?

**Comment by dinhnguyentrunghoa** [comment]
Yes, we use dummy text.But We change the JSON structure to store the dummy text of `Open issues`. After that, using this data to show on the UI.

**Comment by vanbui1995** [comment]
Just note: I added 2 open issues to Hesta Personal Super product, so the warning icon will show when adding Proposed product with Hesta Personal Super
