### ISSUE TITLE
[Strategy] Add new dropdown option on the section title (2h)

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#421]
![9b-Dropdown-in-Section-Names](https://user-images.githubusercontent.com/16713398/71660617-32d26580-2d7e-11ea-85f4-b645f4cfcdb9.jpg)

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa the dropdown options will come from the API

For now, please put: `Client, Partner` and `All` as the options in the dropdown

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa I added `SMSF` here
