### ISSUE TITLE
Implement the layout structure and tables for a new Strategy page.

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#43]
Ref: kodiakorg/financial#40

TODO
---
- [x] Create a new route for Strategy page.
- [x] Prepare the layout for the group of graph/chart at the top of the page.
- [x] Prepare the layout for the left content: Statistic, Graph/Chart, text.
- [x] Prepare the layout for the right content: the Strategy table.
- [x] Prepare the layout for the Drawer.

[Strategy Optimizer V7.pdf](https://github.com/kodiakorg/financial/files/3280342/Strategy.Optimizer.V7.pdf)

**Comment by moewiz** [comment]
PR: https://github.com/kodiakorg/financial-planning-dashboard/pull/39

**Comment by sdharmarajah** [comment]
@moewiz what do you mean: 
- Prepare the layout for the right content: the Strategy table.
- Prepare the layout for the Drawer.

I thought we agreed not to work on these sections?

**Comment by moewiz** [comment]
@sdharmarajah It just the structure, a placeholder component to display the simplest layout. We haven't implemented anything for it yet.
