### ISSUE TITLE
Need to have the 13 possible values from our shared sheet (including “property”) in the dropdown box

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#44]
Q: Do we have a new `Property` option in the list of `Investment` of `Property` asset type?
A: Yes - need to have the 13 possible values from our shared sheet (including “property”) in the dropdown box.

Dropdown values for investment:
> Cash
Fixed Interest
Australian Equity 
International Equity
Property [please see below section]
Growth Alternatives 
Defensive Alternatives
Preservation profile
Defensive profile
Moderate profile
Balanced profile
Growth profile
High Growth profile

**Comment by sdharmarajah** [comment]
@moewiz please confirm - this should not take much time
It should be creating key/value pairs in a hardcoded data-structure

**Comment by moewiz** [comment]
@sdharmarajah Yes, this not take much time.
