### ISSUE TITLE
Implement HOC (with styling) in Strategy page: Graph

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#46]
Ref: #40 

TODO
---
- [ ] Implement HOC for Graph.
- [ ]  Style text (font size, font weight), box shadow, etc.
- [ ] Draw chart with dummy data.
- [ ] Have the option to flip and change it's content.

**Comment by sdharmarajah** [comment]
@moewiz what is this "Apply flipping text" for the graph?

**Comment by moewiz** [comment]
@sdharmarajah, it should be "Have the option to `flip` and change it's content".

**Comment by sdharmarajah** [comment]
OK - that's fine
Can you please update this in the description thanks

**Comment by moewiz** [comment]
@sdharmarajah Sure, I updated. Thanks!
