### ISSUE TITLE
Implement HOC (with styling) in Strategy page: Strategy table

### ISSUE THREAD

**Issue by moewiz** [kodiakorg/financial#52]
Ref: #40 

TODO
---
- [ ] Implement HOC for Strategy table.
- [ ] Render List and list-item.
- [ ] Style text (font size, font weight), add button, checkbox, delete icon, etc.

**Comment by sdharmarajah** [comment]
@moewiz I thought we agreed not to work on this task?

**Comment by moewiz** [comment]
@sdharmarajah I will **not** start this until you approve.

**Comment by sdharmarajah** [comment]
Got it.
I thought all tasks were what we were trying to approve :)
