### ISSUE TITLE
Init Project

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#6]
## Stack
 - [x] create-react-app
 - [x] TypeScript
 - [x] Antd
 - [x] Webpack
 - [x] Formik & Yep
 - [x] React 16
 - [x] Redux
 - [x] Redux-saga
 - [x] React-router 4
 - [x] Eslint
 - [x] Styled-components
 - [x] axios
 - [x] dotenv
 - [x] immutable
 - [x] moment
 - [x] redux revtools

## Files & Folders Structure & Core principles
 - [x] Redux
 - [x] Saga
 - [x] Immutable
 - [x] Devtools & Logger
 - [x] Auth actions
 - [x] Auth reducer
 - [x] Auth interfaces & types
 - [x] Auth Saga
 - [x] React-router
 - [x] Home page
 - [x] Api Utils

## Integrate Antd
 - [x] Apply Antd lib
 - [x] Create MainLayout

**Comment by haunguyen90** [comment]
Finished init project and installed dependencies here 10bdecf217999811889f821e377f07472c844f69
will continue to structuring the project files & folders with Redux, Saga, immutable, antd & styled-components

**Comment by sdharmarajah** [comment]
Jest and Enzyme added too?

**Comment by haunguyen90** [comment]
@sdharmarajah @dinhnguyentrunghoa @moewiz @vienpn91 
I've finished the core principles and structures for the project, please review the code [here](https://github.com/kodiakorg/financial-planning-dashboard/pull/1) and follow the code guide
