### ISSUE TITLE
Make a layout and styles for Add button dropdown

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#68]
- Using Cascader component. (https://ant.design/components/cascader/).
- Style the component like below:
<img width="1093" alt="dropdown-UI" src="https://user-images.githubusercontent.com/16713398/60503849-b1c0e580-9cea-11e9-9e76-4714951c9134.png">

**Comment by sdharmarajah** [comment]
Please use the *hover* effect for the cascader:
`https://ant.design/components/cascader/#components-cascader-demo-hover`

**Comment by moewiz** [comment]
@sdharmarajah Okay, I see.

**Comment by dinhnguyentrunghoa** [comment]
![image](https://user-images.githubusercontent.com/16713398/60801227-d7ddfe00-a1a0-11e9-8b42-b2ab491e7cd1.png)
We should remove the border on the `+` icon
