### ISSUE TITLE
 Formatting and rendering of “`Custom amount/Full value`” dropdowns

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#84]
When the user *clicks* a dropdown for `Custom amount` and `Full value`, the items shown should be:

- `Custom amount`
- `$9,120 (Full value)`

After clicking on of these items:
- If the user clicks `Custom amount`, it should show *`$xx (Custom amount)`* and the user *CAN* edit *xx*
- If the user clicks `Full value`, it should show *`$9,120 (Full value)`* and the user *CANNOT* edit *$9,120*

Note (reminder): $9,120 is a value we will send from the backend

**Comment by moewiz** [comment]
Screenshot:
<img width="626" alt="Screen Shot 2019-07-18 at 5 39 59 PM" src="https://user-images.githubusercontent.com/12948375/61451667-18e5c780-a984-11e9-94b8-6c69d5d7d9e8.png">
