### ISSUE TITLE
Build and apply the JSON structure for the first API call

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#93]
Now, we have separated JSON file for all sections and drawer.
But we want to load all data in one API call. We should join them together.
TODO: 
- [ ] Join JSON file
- [ ] Change the code to show from the new joined JSON

**Comment by sdharmarajah** [comment]
@dinhnguyentrunghoa 
For the `JSON` please see the extra key I added here: https://github.com/kodiakorg/financial/issues/95
