### ISSUE TITLE
Send the modifications through the API 

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#95]
Sending a JSON included a lot of data is bad practice. We will optimize the API call on the next phase.
Because of that, the sent data to the server will have the `Modifications` part. This part will contain only the changed value and some parameters to know where the change is. 

JSON structure: 
`{
  data: {
    // the JSON for all page (include the changes)
  },
  modification: {
    // the changed only 
  }
} `

**Comment by sdharmarajah** [comment]
Thank you @dinhnguyentrunghoa 

For this first version of the API integration, please also include **what the original value was**

i.e. 
`original: { // the key and original value of the key, before the change  }`
